- BigDebuffs.lua
Didn't somehow indent the whole file this time ;)
> Spell updates

- BigDebuffs.lua
I added BFA Polymorphs to display on frames.
> BFA Polymorphs

- BigDebuffs.lua
SSIA, really - but it is a very nice addition for this addon (especially for arenas).
> Add grounding totem

- BigDebuffs.lua
Added Gladiator's Maledict to the cc tracking.
This is primarily for areas to show when a player has this debuff.
> Add Gladiator's Maledict

- Retail.lua
- Fix for Maledict
- Add [Forbidden Obsidian Claw](https://www.wowhead.com/spell=313148/obsidian-claw)
Closes: #48
> Maledict and Forbidden Obsidian Claw

- BigDebuffs.lua
TidyPlates should use the same 'carrier' frame but haven't confirmed.
> Compatability with NeatPlates

- BigDebuffs.lua
I finally found the time to create a pull request for this, see https://github.com/jordonwow/bigdebuffs/issues/103.
> Added support for Threat Plates to BigDebuffs.

- Retail.lua
Rogue PvP talent that disarms the target.  Other disarms are available, make dismantle available as well.
> Add Rogue Spell - "Dismantle"

- Retail.lua
some formatting as well
removed touch of death
> Fixed Thoughtsteal 

- BigDebuffs.lua
Hi, I'm the current maintainer of TidyPlates and we've had a couple users submit a request to make BigDebuffs work with it. I'm not 100% sure on how your addon works internally so the quick fix I've done might not be perfect, but it seems to be working and it's what I'd expect how it should work. There also was an existing comment that guessed it worked this way.
> added support for TidyPlates

- BigDebuffs.lua
> better portrait icon masking

- Retail.lua
I'll probably regret this one, because people will actually start decursing this, but oh well
> Added shackles of malediction cast and healing absorb debuffs

- BigDebuffs.lua
Add support for bdUI, but also for any oUF based nameplate addons.
> adding bdUI/oUF support

- Retail.lua
Keeper of the grove and Consecutive Concussion
> Added Druid Immunity and Hunter Stun

- Retail.lua
> Added new immunity trinket from 9.2

- BurningCrusade.lua
Add missing Orc racial `Blood Fury`.
> [BUG FIX] Add missing Orc racial `Blood Fury`

- Retail.lua
> Added Gladiator's Eternal Aegis

- BigDebuffs_Mainline.lua
https://www.wowhead.com/spell=228358/winters-chill
Ideally I'd like to see the number of stacks on it as well but I wasn't sure how to add that.
> add Winter's Chill

- .gitignore
- BigDebuffs.lua
- BigDebuffs.xml
It is a quick fix without rewriting how the auras are handled and should work backward compatible. 
I working to rewrite how auras from 10.0 are handled.
> Fix to retail version (number of spells and tooltips)

- BigDebuffs_Mainline.lua
Add [Dragonrider's Initiative](https://www.wowhead.com/spell=378409/dragonriders-initiative) and [Dragonrider's Compassion](https://www.wowhead.com/spell=388380/dragonriders-compassion) spells
> Add dragonriding spells

- BigDebuffs.lua
- BigDebuffs.toc
- BigDebuffs_Mainline.lua
Added the basic stuff for evoker, more things should be added, but atleast will make the addon work for evokers properly
> Added some basic stuff for evokers

- BigDebuffs_Mainline.lua
Update the following evoker spells:
- Correct Landslide spell ID
- Add Nullifying Shroud
- Add Obsidian Scales
> Update a few evoker spells

- BigDebuffs.lua
> Fix CompactUnitFrame compare nil error

- BigDebuffs_Mainline.lua
Removed spells replaced in Dragonflight, updated spell IDs to their correct ID, and added additional Evoker spells.
> Updated spells list for Retail (Mainline)

- BigDebuffs_Mainline.lua
Added Grievous Wound request from #574 , Berserker Shout (Warrior group Fear removal), and Glimpse
> Request for Grievous Wound

- BigDebuffs.lua
- BigDebuffs.xml
reverted your PR and implemented a hack
> this feels like a hack, why does the player frame need a special case

- BigDebuffs.lua
Basic changes to BigDebuffs.lua to add support for Pitbull Unitframes out of the box.
> Add PitBull Unitframe Suport

- BigDebuffs_Mainline.lua
Clash to a ROOT instead of CC, corrected Necrotic Wounds and Frostbite to their current spell IDs, and corrected typos on punctuation/format with nounitFrames
> Small edits

- BigDebuffs_Mainline.lua
- Added Searing Glare (Paladin).
- Edited formatting to make everything in sync again
> Small Editing

- BigDebuffs_Mainline.lua
This PR adds [Thunderous Roar](https://www.wowhead.com/spell=397364/thunderous-roar) and [Death Wish](https://www.wowhead.com/spell=199261/death-wish) for warriors.
> Add Thunderous Roar and Death Wish

- BigDebuffs.toc
Updates retail for patch 10.1.7
> Update retail version to 10.1.7

- BigDebuffs.lua
- BigDebuffs_Mainline.lua
- Custom.lua
^see title. Discarded the previous pull request.
Same as before. Hope you'll merge.
> Hide unwanted Debuffs by ID (Custom.lua)

- BigDebuffs_Mainline.lua
Added missing Warlock talent "Horrify" that alters Fear spell id.
> Add Warlock talent "Horrify" fear talent spell id.

- BigDebuffs_Mainline.lua
Added: 
- Ultimate Penitence (Discipline Priest)
- Piercing Howl (Root) (Warrior)
Edited:
- Fear (Horrify) to a child
Removed:
- Aspect of the Wild (Beast Mastery Hunter)
- Dreadblades (Outlaw Rogue)
- Rapid Contagion (Affliction Warlock)
> 10.2 Patch Initial Changes

- BigDebuffs_Wrath.lua
add max rank frost ward spell id
add max rank fire ward spell id
> Update BigDebuffs_Wrath.lua to include frost ward and fire ward max rank

- BigDebuffs_Cata.lua
Added Ring of Frost and Improved Cone of Cold spell ids.
> Add two missing mage spell ids

- BigDebuffs_Cata.lua
https://github.com/jordonwow/bigdebuffs/issues/734
> added Cauterize and moved Skull Bash to interrupts section 

- BigDebuffs_Cata.lua
https://github.com/jordonwow/bigdebuffs/issues/735
> Added Solar Beam

- BigDebuffs_Cata.lua
changed felguard stun
added VT dispel
added new DK pet abilities 
added new hunter pet abilities
> cata updates

- BigDebuffs_Cata.lua
https://www.wowhead.com/cata/search?q=Demon%20Soul#uncategorized-spells
> added warlock Demon Soul

- BigDebuffs_Cata.lua
priest aura mastery https://www.wowhead.com/cata/spell=96267/strength-of-soul 
rogue defensive https://www.wowhead.com/cata/spell=74001/combat-readiness
> added Combat Readiness and Strength of Soul

- BigDebuffs_Mainline.lua
Added Evoker Scalecommander's versions of **Deep Breath** and **Breath of Eons**
> Evoker Scalecommander Breaths

- BigDebuffs_Mainline.lua
**Druid**
- Reactive Resin removed from CC/Debuff Offensive
**Mage**
- Polymorph (Mosswool) added
**Paladin**
- Divine Plea added back
**Rogue**
- Sepsis removed
> 11.0.5 Changes

- BigDebuffs.lua
Reverts jordonwow/bigdebuffs#252
> Revert "feat: add support for GladiusEx frames"

- BigDebuffs_Mainline.lua
Beast Mastery Hunter's Call of the Wild added. (Request #826 )
> Call of the Wild

- BigDebuffs_Mainline.lua
**Death Knight**
- Price of Progress added
- Breath of Sindragosa ID changed
- Abomination Limb changed to Legion of Souls
**Monk**
- Zen Meditation and Guided Meditation removed
**Mage**
- Added Nether Flux
> 11.2 Patch Updates

- BigDebuffs_Mists.lua
Added Black Arrow
Added Soul Reaper for all dk specs
Added Dematerialize for monks
Added Ascendance for all shaman specs
Added Havoc
> Added additional important spells
