BigDebuffs.lua
Added Ironfur Defensive cooldown for Guardian Druids.
Tested spell ID.
=> Missing Spell: Ironfur

BigDebuffs.lua
Hi Jordon
The spell ID for Death Knights' Dancing Rune Weapon changed from 49028 to 81256.
I suggest also changing it from an Offensive to a Defensive spell as it only gives a very marginal damage boost. The key trait of this spell is the 40% parry for tanks.
=> Dancing Rune Weapon: new spell ID and type

Retail.lua
Added Entrenched in Flame, the pvp talent that makes conflag a root.
=> feat: warlock root

Classic.lua
Tiny PR to add [the haste buff granted from Manual Crowd Pummeler](https://classic.wowhead.com/spell=13494/haste) to the list of classic spells.
This item is used regularly by feral druids as their big dps cooldown so I believe it's fit for purpose here
=> Adding MCP haste buff

Classic.lua
Add [Spell Vulnerability](https://classic.wowhead.com/spell=23605/spell-vulnerability) to Other Buffs category.
Resolves #115
=> #115 Add Nightfall to Other Buffs

Retail.lua
Broken in https://github.com/jordonwow/bigdebuffs/commit/79db2c21b9ff816b0449c97d3eb9dd3356ad7498#diff-97d6ded70ce5188565623eeab389cfdb01a28102deac0689541789b612c19d41L168
My friend and I tested my change and confirmed it works.
=> Fix lightning lasso spell ID

BigDebuffs.lua
A small fix that handles ElvUI party unit frames with or without showing the player. The case when BD shows on wrong players. Will fix #156
=> Fix ElvUI Party/Player frames missplased icons.

BigDebuffs.lua
Some people experience auras unexpectedly appearing and then remaining stuck on nameplates (see #236) and the personal resource display (see #234). It seems like sometimes the nameplates (particularly those that are supposed to be disabled) can occasionally inherit the displayed icon from another nameplate, and will then never expire. 
**_I don't know what is actually causing the problem_**, but discovered that moving the initial checks in 
`function BigDebuffs:UNIT_AURA_NAMEPLATE(unit)` to the end of that block and hiding/disabling those frames, seems to prevent the issue from showing up. I don't fully understand exactly how everything in this addon works yet, but I guess that worst-case scenario there will now be a little more processor work, particularly for people who have some …
=> Fix for false icons sticking to nameplates

BigDebuffs.lua
Sorry, brackets are hard :-) Thanks for the quick merges.
=> fix: prevent reeinitializing of unitframe anchor settings

BigDebuffs.lua
When using manually anchored party frames, they should no longer show while in a raid group larger than 5 players.
=> Fix #261: party frames showing in large raid groups

Retail.lua
Hey. So I've went through every classes spellbook, talents and pvp talents to verify the spell id's and add missing stuff / remove old no longer existing stuff in BigDebuffs. I've also added a bunch of things that I think should have the option to be tracked.
Most of it should be straightforward from looking at the diffs, but some notes on stuff that might not be obvious:
- Changed Resto Druid Incarnation to track the Incarnation buff itself rather than the Tree of Life form buff. The way this cooldown works is it gives you one 30 sec duration buff ("Incarnation") that lets you shift into Tree of Life form (another buff, "Incarnation: Tree of Life"). This second buff does not have a duration, it's just a shapeshift form buff, thus I think tracking the Incarnation buff is just more …
=> Spell updates

Retail.lua
Added Convoke the Spirits and the Holy Priest resurrection legendary.
Removed a few old spell IDs and fixed the parents. (Lightning Lasso, Thorns)
Renamed Honor Talent to PvP Talent for consistency.
=> Spells updates

BigDebuffs.lua
Currently, BigDebuffs get anchored to ElvUI arena frames although they are disabled.
This PR applies the mechanism preventing this bug from happening with party frames to arena frames.
Quite possibly this bug affects player/target/raid as well.
=> fix: dont anchor arena debuffs to hidden elvui frames

Retail.lua
Hey, so I've been working on a spell update / polish. Most of the diffs are pretty straightforward, but here's a breakdown of the changes:
* Spell id corrections / removals were all tested (in some cases vs both players and npcs where I felt like I need to confirm that) and/or I've identified the reason they were wrong in the first place (some ids were linking to spells without auras - they were just the spell ids of the talents/spells themselves, not of the buffs/debuffs). Also removed some old spells that simply don't exist anymore.
* Added a bunch of stuff that I think is important, particularly a lot of Covenant abilities and some important Shadowlands Legendary effects were missing. I've been very careful with this however, since this addon only shows one thing at a time. In that …
=> Retail spell updates / polish

Retail.lua
A few times in arena a player would be resurrected out of no where and I'd be super confused.
This should help visualize when a res totem is out.
=> Added Ancestral Protection (Shaman Resurrection Totem)

BigDebuffs.lua
There are no permissions concerns with nameplate anchors. Fix
a bug where anchoring to nameplates chooses the wrong anchor point
and gets stuck due to being in combat.
=> Fix combat nameplate anchor bug.

Retail.lua
9.1.5 Nimble Steps and Keefer's Skyreach added, both were missing and are crucial spells to gameplay.
=> 9.1.5 Nimble Steps and Keefer's Skyreach added

BigDebuffs.lua
Mirrors the API change from the previous patch: https://www.townlong-yak.com/framexml/42698/CompactUnitFrame.lua#1221
To live: https://www.townlong-yak.com/framexml/live/CompactUnitFrame.lua#1231
Per https://www.townlong-yak.com/framexml/42698/CompactUnitFrame.lua#1438 the deleted function was simply picking its 12th argument, so this change gives (most of) the enclosing function's arguments names, and then picks the 12th by name.
The only testing I've done for this is joined a party and made sure I could see >3 hots on myself.
=> Use varargs unpacking instead of removed CompactUnitFrame_Util_IsBossAura

BigDebuffs.lua
Basically went down [this diff](https://www.townlong-yak.com/framexml/42852/CompactUnitFrame.lua/diff) and looked for any functions with changed parameter lists. Found `CompactUnitFrame_Util_IsPriorityDebuff`, `CompactUnitFrame_Util_ShouldDisplayDebuff` and `CompactUnitFrame_UtilShouldDisplayBuff`.
Tested in retail, not getting errors any more and worked in LFR. I did experience an issue with some raid frame groups misbehaving after people joined/left LFR, not sure if it was related to these changes or even this addon; reloading UI fixed it.
Also, `CompactUnitFrame_UpdateAuras` looks like it now takes two additional parameters `isFullUpdate` and `updatedAuraInfos`. I didn't attempt to follow up on this, since it's not clearly causing a problem and the first parameter `frame` is still the …
=> Fix CompactUnitFrame_Util functions with updated parameters

Retail.lua
I know technically Ice Form should be parented to Icy Veins, but Icy Form does have a very unique functionality in addition to the damage portion: stun immunity.
By removing the parent, we can allow players to config Ice Form and Icy Veins separately, e.g., someone just wants to see the stun immunity on nameplates so he doesn't might bash / HOJ into it.
=> Allow Ice Form to config separately from Icy Veins

Retail.lua
Added the cooldown debuff because the resurrection buff portion does not proc unless the priest heals a party member. Would sometimes get tricked by priest not healing and not having the buff portion pop up on plate.
=> Spell update to priest resurrection legendary

Retail.lua
The nightfae rogue ability Sepsis has two different components [- a debuff on a target](https://www.wowhead.com/spell=328305/sepsis) and a [buff ](https://www.wowhead.com/spell=347037/sepsis)that the rogue gets when sepsis expires. [Source](https://www.wowhead.com/spell=328305/sepsis#comments:id=3283904)
Added the debuff to the rogue list of offensive debuffs.
=> Added sepsis debuff to rogue list

BigDebuffs_Mainline.lua
This pull requests adds the dispellable Explosive Shot debuff from hunters' necrolord legendary.
=> Add Explosive Shot offensive debuff

BigDebuffs_Mainline.lua
Adding major feral bleeds.  Currently bleeds can be dispelled by hunters as well as the Kyrian potion. 
Verified by making changes to local and testing that the bleeds show up in raid frames.
=> adding major feral bleeds

BigDebuffs.lua, BigDebuffs_Wrath.lua
- shaman earth shock doesnt kick anymore
- warlock nether protection is now spell damage decrease vs immunity
- remove spells that dont exist anymore
=> wrath: spell fixes

BigDebuffs.lua
- paladin improved concentration aura
- shaman focused mind
for some reason the talentIndex for GetTalentInfo is not counted top-down left-right anymore, so that's why the values seem out-of-place, but tested to work (unlike #406 , where I just assumed it works like it used to)
=> wotlk talent fixes

BigDebuffs_Wrath.lua
- add in feral faerie fire
- only 1 rank of 'regular' and 'feral' now
Signed-off-by: jarves <jarveson@gmail.com>
=> wrath: fix faerie fire

BigDebuffs.lua, BigDebuffs.toc, BigDebuffs.xml
Closes #421 #423 
Took a stab at support for Dragon Flight.  Definitely ran into some interesting issues with retail vs classic.
This PR is pretty close to complete, some of it is not pretty, but it works 😃 Might work on some refactor later, just wanted this working while I test classes.
2 known issues, I have not figured out how to support new Blizzard party frames, I have some code commented out that is close, but not quite there, I moved on as I assume most users don't use party frames, but rather raid style frames.  2nd issue is when you use the Test feature in the settings menu the frames are movable, not sure this is actually new or not, but noticed it while I was testing anchors on the new frames.
Last thing to note, had to update a bunch of Ace libs, no idea how that works in the …
=> updates to support dragon flight

BigDebuffs.lua
#425 
this fixes the displaying of 6 buffs, but causes taint to the function ClearTarget()
No idea why, but the only place I noticed that it matters is when exiting the new blizzard edit mode, the exit will not clear your target or focus and gives an error.
Figured I would submit and see if anyone knows how to fix that.
=> fix displaying 6 buffs

BigDebuffs.lua
Closes #426 
In Wrath ArenaEnemyFrame1ClassPortrait [1-5] are not loaded on login or likely anywhere outside an arena.  I did what little testing I could, but don't have an easy way to arena in Wrath.
=> allow anchor to be nil if frame does not exist

BigDebuffs.lua
When using the "Show Blizzard Nameplates for Neutral and Enemy Units" or "Show Blizzard Nameplates for Friendly Units" option/s in Threat Plates, BigDebuffs does not show on the nameplates. Using Blizzard nameplates when ThreatPlates does not show a nameplate fixes the problem.
=> Allow using Blizzard nameplates in Threat Plates

BigDebuffs.lua
Got this idea from another addon that might be a fix for potential taint issues when opening the editmode. I just added this function  
function checkFrame(frame)
if not issecurevariable(frame, "action") and not InCombatLockdown() then
frame.action = nil
frame:SetAttribute("action");
end
end
and used it in every hooksecurfun call like 
for _, frame in ipairs(ActionBarButtonEventsFrame.frames) do
hooksecurefunc(frame, "UpdateAction", checkFrame);
end
But this may need more testing because I think it create other issues. I use biggerbuff addon for druid to show more than 3 buffs. But it's only for showing more than 3 buffs on raid frame. Bigdebuff is more complicated so this is just a suggestion. Maybe it gives you an idea how to fix the issue.
=> Potential fix for the taint issue

BigDebuffs.lua
When not in a party or disabling "Display player" in ElvUI party group settings, no anchor would be found, this should fix the issue.
=> Fixed ElvUI anchor when no player in party frame

BigDebuffs.lua
Please, it would be great if someone could look over the commit. I'm rather new to the addon development. This change of line of code hasn't produced errors for me tonight. just moving these two lines out of the hooksecurefunc and it's only above the increase maxbuff function.
for _, frame in ipairs(ActionBarButtonEventsFrame.frames) do
hooksecurefunc(frame, "UpdateAction", checkFrame);
=> Maybe a fix to the C stack overflow

BigDebuffs_Mainline.lua
Dragonflight has different spell ID for Mindgames. This PR fixes it:
Also remove Greater Fade since it's no longer a thing in 10.0
=> Fix the spell ID of Mindgames

BigDebuffs_Mainline.lua
As the PR title states, just adding the missing Deathmark spell that Rogues got in Dragonflight
=> Adding Deathmark to Rogue's Spell List

BigDebuffs.lua
This is accounted for in 'classic' mode, but not on mainline.
=> Account for Cauterizing Flame (Evoker) on mainline

BigDebuffs_Mainline.lua
Added Water Unleashed (Shaman PvP talent choice for 50% reduced damage and healing for 6s while in the whirlpool) and Oppressing Roar (Evoker class talent choice) in offensive debuffs category.
=> Water Unleashed/Oppressing Roar

BigDebuffs.lua
ive isolated this issue using only bigdebuffs active but have been unable to reliably reproduce it, yet it does happen frequently, especially considering the need to /reload before every single arena match due to so much tainting going on with addons. not exactly sure what this fix does except perhaps adjusting the frame strata, but it seems to completely fix the issue. for the record, this only occurs with the player frame. 
pic showing the issue: https://i.imgur.com/NFV8lC7.png
the barkskin icon is behind my playerframeportrait
=> fix from issue #435

BigDebuffs.lua
this ended up being a bad change and should be reverted. while it does fix this common issue with the player frame, it fucks up the target/focus frames by causing the bd portrait icon to have a higher level than the portrait boarder so the icon sits on top of the graphic:
https://i.imgur.com/MQn8Ojs.png
not sure what the fix is for only the player frame
=> Revert "fix from issue #435"

BigDebuffs.lua
After playing the game (continuous arena queues) for a while, the addon would just randomly block all my action bars.
Pressing the keybinds is completely broken while mouse click still works.
After enabling taintLog level 2, here is the possible culprit.
The first block in the taint log is:
`An action was blocked in combat because of taint from BigDebuffs - ActionButton1:SetAttribute()`
Looking back from there, the `SetAttribute` taint happens around here:
```
1/22 14:48:19.419      Interface/FrameXML/ActionButton.lua:486 OverrideActionBarButton1:UpdateSpellHighlightMark()
1/22 14:48:19.419      Interface/FrameXML/ActionButton.lua:392 OverrideActionBarButton1:Update()
1/22 14:48:19.419      Interface/FrameXML/ActionButton.lua:362
1/22 14:48:19.419 …
```
=> Fix action bar block

BigDebuffs_Mainline.lua
TOC 100005
Added:
- Salvo
- Shadow Covenant
- Schism
Edited:
- Flame Shock and Curse of Weakness to show on only Raid Frames by default
Removed:
- Double Tap
=> Patch 10.0.5 Changes

BigDebuffs_Mainline.lua
Not a fix for the current issues with FPS. I just decided to go through the Mainline file again to clean up incorrect spell IDs, spells currently not in Dragonflight, or one spell removed from the game entirely (Spirit Link PvP talent) to potentially not cause any issues in the future.
Added:
- Sentinel (Protection Paladin)
- Bloodshed debuff (Beast Mastery Hunter debuff)
- Stormkeeper buff (Restoration Shaman)
Edited:
- Binding Shot to a Crowd Control from Root (Changed in DF)
- Fortifying Brew
- Thunderous Paws from Shadowlands conduit ID to DF
- Curse of Tongues
- Sudden Impact to Sudden Death text
- Bladestorm (Hurricane) to a parent of Bladestorm talent
Removed:
- Tremble Before Me Legendary
- Roll Out Legendary
- Cheap Tricks Outlaw PvP talent
- Spirit Link PvP talent (removed from …
=> Mainline spells list update

BigDebuffs_Mainline.lua
Adding in Orbital Strike buffs of Incarnation: Chosen of Elune and Celestial Alignment when talented into Orbital Strike
=> Incarn/Celestial Alignment Edits

BigDebuffs_Mainline.lua
Deleted spells removed from the game this patch and edited Coordinated Assault Spell ID. Added Phase Shift, Soul Rip, Wild Attunement, Sticky Tar Bomb, and Burrow.
=> 10.1 Spell Updates

BigDebuffs_Mainline.lua
I did the work through the PTR client and Wowhead's PTR website so if things end up changing on Live after maintenance tomorrow, I'll submit edits. Interface TOC should be 100105.
Added:
- High Winds (Druid)
- Spatial Paradox, Blistering Scales, Time Skip, Seismic Slam (May have to edit this spell's spell ID), Breath of Eons (Evoker)
- Ice Cold (Mage) and Frost Bomb (Frost Mage)
- Hand of Divinity, Divine Plea, and Denounce (Holy Paladin)
- Luminous Barrier (Discipline Priest)
- Oblivion (Affliction Warlock)
Edited:
- Mass Invisibility spell ID change for 10.1.5
Removed:
- Prismatic Cloak (Mage)
- Holy Avenger (Paladin)
=> 10.1.5 Patch Spell Updates

BigDebuffs_Mainline.lua
I thought it would be a short duration buff similar to Thorns so I think it's better to remove it for now. It might be useful in the BUFF_OTHER category in the future. Small change so push this whenever :)
=> Removing Blistering Scales

BigDebuffs.lua, Options.lua
Added the ability to wrap the debuffs after specified amount. 
The attached images show examples of all anchors with wrap set to 3 debuffs and max debuffs of 11
=> Raid frame debuff wrapping option

BigDebuffs_Mainline.lua
Adds the warlock spell [Phantom Singularity](https://www.wowhead.com/spell=205179/phantom-singularity).
=> Add Phantom Singularity

BigDebuffs_Vanilla.lua
The main target cowers and other targets will be feared. Adapted from your code [here](https://github.com/jordonwow/bigdebuffs/blob/cc347b0f12fd29c57271b36a9de6427e99ef560b/BigDebuffs_Mainline.lua#L606C11-L606C61).
[main target](https://www.wowhead.com/classic/spell=20511/intimidating-shout)
[other targets](https://www.wowhead.com/classic/spell=5246/intimidating-shout)
=> Add intimidating shout

BigDebuffs_Wrath.lua
The spell ids for vampiric touch and unstable affliction are **missing** so this pull request adds them. Should fix https://github.com/jordonwow/bigdebuffs/issues/627
```
47843, -- Unstable Affliction
48160, -- Vampiric Touch
```
Furthermore the weakened soul debuff for priests can often disappear as it loses priority and at the moment, isn't adjustable. This should fix https://github.com/jordonwow/bigdebuffs/issues/595 and https://github.com/jordonwow/bigdebuffs/issues/619
=> Support for latest spell ids for warning spells and weakened soul for priest

BigDebuffs_Mainline.lua
Now that Living Bomb does an ungodly amount of damage, I've found it very useful to track.
=> Add Living Bomb mage debuff

BigDebuffs_Vanilla.lua
Shackle Undead is already on the TBC, Wrath, Cata, and Mainline versions of BigDebuffs and it would be helpful to have in Vanilla as well, especially for the Atal'ai Defenders fight in Season of Discovery.
=> Add Shackle Undead to BigDebuffs_Vanilla

BigDebuffs.lua
Currently, with Threat Plates v11.2.x, BigDebuffs' icons will not be shown when TellMeWhen is enabled as well. 
The basic issue is that frame.TPFrame:IsShown() in nameplateAnchors (in BigDebuffs.lua) for Threat Plates is called before Threat Plates was updated, e.g., the frame is not yet shown, after a NAME_PLATE_UNIT_ADDED event was fired. It's explained better an in more detail here: https://github.com/ascott18/TellMeWhen/issues/2064#issuecomment-1405975273.
The below solution is based on Threat Plates providing a function that returns an anchor to which BigDebuffs can link its icons. As this requires Threat Plates to also be updated to v11.2.4 (https://github.com/Backupiseasy/ThreatPlates/releases/tag/11.2.4), a fallback solution is added. (I guess the comment about the fallback could …
=> Fixed an incompatibility with Threat Plates where BigDebuffs' icons here not shown

BigDebuffs.lua
I noticed that even with ElvUI's Party Frames disabled, BigDebuffs wasn't appearing on other Party Frames, like Cell's. With this fix, BigDebuffs is now showing up on the Cell addon frame, and potentially on other party frames as well.
=> Fix issue preventing BigDebuffs usage on party frames other than ElvUI

BigDebuffs.lua
fixes #725 
The error message mentioned in #725 triggers when mousing over a warning bigdebuff because `SetSpellByID` is expecting an integer spell ID, but is receiving a boolean (`true`)
=> fix: add spell ID to warning debuff entry

BigDebuffs_Vanilla.lua
Added creatures Net ability for Vanilla Hardcore
https://www.wowhead.com/classic/spell=6533/net
=> Added creatures' Net ability for Vanilla Hardcore

BigDebuffs_Mainline.lua
Mostly just additions or removals for what is in the pre patch currently. I'll have to look at Hero talents soon.
**Death Knight**
- Added Tightening Grasp (Gorefiend's Grasp silence), Lesser Anti-Magic Shell, and Ice Prison (Chains of Ice root)
**Druid**
- Edited Rage of the Sleeper to Defensive Buff
- Removed High Winds and Wild Attunement
**Hunter**
- Added Survival of the Fittest (Defensive)
- Removed Flayed Shot, Steel Trap
- Edited Diamond Ice
**Mage**
- Removed Radiant Spark
- Corrected Living Bomb
**Monk**
- Removed Serenity and Skyreach
**Paladin**
- Added Radiant Glory buffs of Avenging Wrath and Crusade for Retribution 
- Removed Divine Plea
**Priest**
- Removed Mind Bomb
- Fixed white space on Schism
**Shaman**
- Removed Stormkeeper (Restoration)
**Warlock**
- Removed Nether …
=> TWW Pre Patch

BigDebuffs_Cata.lua
WoWHead Links:
[47481](https://www.wowhead.com/cata/spell=47481/gnaw)
[91800](https://www.wowhead.com/cata/spell=91800/gnaw)
Notice the 91800 ID has the debuff tooltip displayed on WoWHead, but the 47481 ID doesn't
=> fix: change gnaw spell ID

BigDebuffs.lua, Options.lua
not sure if this complies with format
- replaced GetSpellInfo to use C_Spell.GetSpellName instead of C_Spell.GetSpellInfo because it looked like the usage was mostly for retrieving names
- UnitDebuff and UnitBuff now uses C_UnitAuras
- AuraUtil.UnpackAuraData as it seems this fixes debuffs/buffs not showing on nameplates (interrupts were still shown), apparently used for unpacking return values with backwards compatibility
=> TWW fix deprecated functions

BigDebuffs_Mainline.lua
First round of Hero talent additions.
**Death Knight**
- Added Death Charge (Death's Advance)
**Evoker**
- Added Shape of Flame debuff
**Hunter**
- Added Catch Out (Root)
**Monk**
- Added Celestial Conduit (Buff)
**Shaman**
- Added Nature's Swiftness and Ancestral Swiftness
**Warlock**
- Added Malevolence
**Warrior**
- Added Shield Charge (Stun)
- Added another version of Bladestorm
=> TWW Update #2

BigDebuffs_Mainline.lua
Added Horsemen's Aid's Anti-Magic Shell and Gravity Lapse (Supernova Hero talent root).
Closes #784 and #782
=> Small spells update

BigDebuffs.lua
Is it possible to implement a change so that the UI-HUD-UnitFrame-Player-Portrait-Mask is only set when the new Blizzard PlayerFrames are actually set?  think this could enhance compatibility and help avoid faulty alignment with unit frames that do not use the new Blizzard frames like this:
=> Set the atlas only if the new frame textures are actually present - compatibility adjustment

BigDebuffs.lua
Follow-up pull request to #785 because I had forgotten a check for the current retail version, as the PlayerFrameContainer only exists there 😞 
We should first check if we are on retail before accessing the PlayerFrameContainer, as otherwise an error will occur on older versions like Cata or Classic.
Should also fix: https://github.com/jordonwow/bigdebuffs/issues/786#issuecomment-2341565908
=> compatibility adjustment - old versions

BigDebuffs_Mainline.lua
These buffs are full immunities that can occur in the open world in Khaz Algar. These two IDs are only the short buff when the immunity is triggered, not the indefinite buff that indicates the protection is active.
After testing, it seems that aura ID 442999 is defunct, and only 443026 is used for General's Phalanx. That said, there could still be a strange case where 442999 is used, so it may need to be added later.
Otherwise, both of these have been tested in the open world.
=> Add General's Phalanx and Bulwark to mainline

BigDebuffs_Mainline.lua
Aura Mastery has different effects based on the current aura (https://www.wowhead.com/spell=31821/aura-mastery)
The effect with Concentration Aura is by far the most game-altering one: `Affected allies immune to interrupts and silences.`
Since all variants share the same icon, I propose changing Aura Mastery to _only_ display when affecting Concentration Aura.
=> Change Aura Mastery to only show the kick-immune effect
